apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: log-service
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: log-service
  template:
    metadata:
      labels:
        run: log-service
    spec:
      containers:
      - name: log-service
        image: gcr.io/death-star-poland/log-service:v1
        env:
        - name: PLANET_SERVICE_TARGET
          value: dns:///planet-service:50061
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: log-service
  name: log-service
spec:
  ports:
  - name: grpc
    port: 50081
    protocol: TCP
    targetPort: 50081
  selector:
    run: log-service
  type: LoadBalancer