apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: score-service
  name: score-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: score-service
  template:
    metadata:
      labels:
        run: score-service
    spec:
      containers:
      - name: score-service
        image: gcr.io/death-star-devoxx-fr/score-service:v1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: score-service
  name: score-service
spec:
  ports:
  - name: grpc
    port: 50071
    protocol: TCP
    targetPort: 50071
  selector:
    run: score-service
  type: LoadBalancer